### ISSUE TITLE
Supporting multiple targets

### ISSUE THREAD

**Issue by eeshwar-eventogy** [newrelic/newrelic-ios-agent-spm#20]
If you have a project with multiple targets, there is no way to add the framework to other targets.

## Description

For other SPM frameworks, after adding it to my main target, I can go to the other targets general settings, and under Frameworks, Libraries, and Embedded Content I can manually add the new framework. But in the case of NewRelic, it does not appear in this list so can not be added to other targets.

## Steps to Reproduce

Add the package via SPM, select the main target.
Go to another target > General > Frameworks, Libraries, and Embeded Content
Click + to add a new one
New Relic is not available.

## Expected Behavior

New Relic should be available as a framework to add to other targets.

## Your Environment

Swift 5
XCode 14.1
MacOS Ventura 13.0
New Relic Agent 4.7.0

**Comment by edAtRei** [comment]
This issue is affecting me as well. Would really love to see a fix!

**Comment by cdillard-NewRelic** [comment]
@eeshwar-eventogy @edAtRei 

I've pushed a new public branch to this repository named `fix-package-multiple-targets`

If you can please change your NewRelic SPM dependency in Xcode to use this branch? 

This should fix the issue with NewRelic not showing up in the  "Frameworks, Libraries, and Embedded Content" area of other targets.

We'll make sure this is fixed in our next tagged releases.

Please keep in mind that you'll want to switch back to integrating NewRelic via release tags when our next release comes out. Keep an eye on our [iOS agent release notes](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/ios-release-notes/) for that.
